LastHomeRoles = LastHomeRoles or {}

print("[LastHome] LastHomeRoles charge - " .. tostring(18) .. " roles")

local Roles = LastHomeRoles

Roles.MODULE = "LastHome"

Roles.ROLE_ORDER = {
    "soldat", "voleur", "local_", "medic",
    "rambo", "sniper", "agent", "samourai", "geek",
    "survivaliste", "pompier", "athlete", "eclaireur",
    "demolisseur", "invincible", "mule", "builder",
    "civil",
}

Roles.ROLE_NAMES = {
    soldat = "Soldat",
    voleur = "Voleur",
    local_ = "Local",
    medic = "Medic",
    rambo = "Rambo",
    sniper = "Sniper",
    agent = "007 Agent",
    samourai = "Samourai",
    geek = "Geek",
    survivaliste = "Survivaliste",
    pompier = "Pompier",
    athlete = "Athlete",
    eclaireur = "Eclaireur",
    demolisseur = "Demolisseur",
    invincible = "Invincible",
    mule = "Mule",
    builder = "Builder",
    civil = "Civil",
}

Roles.ROLE_INFO = {
    soldat = { name = "Soldat", summary = "Combat / defense", strengths = "Tir, couverture, melee" },
    voleur = { name = "Voleur", summary = "Loot furtif", strengths = "Crowbar, discretion, sorties" },
    local_ = { name = "Local", summary = "Reparations / ressources", strengths = "Outils, craft, logistique" },
    medic = { name = "Medic", summary = "Soin / support", strengths = "Soins lourds, stabilisation" },
    rambo = { name = "Rambo", summary = "Tank melee", strengths = "Hache, endurance, breches" },
    sniper = { name = "Sniper", summary = "Longue distance", strengths = ".308, lunette, couverture" },
    agent = { name = "007 Agent", summary = "Agent secret / elimination silencieuse", strengths = "PPK silencieux, MP5SD6, discretion" },
    samourai = { name = "Samourai", summary = "Katana / mobilite", strengths = "Lames, vitesse, precision" },
    geek = { name = "Geek", summary = "Electronique / pieges", strengths = "Bidouille, alarmes, gadgets" },
    survivaliste = { name = "Survivaliste", summary = "Nature / autonomie", strengths = "Pieges, loot, autonomie" },
    pompier = { name = "Pompier", summary = "Sauvetage / anti-feu", strengths = "Hache, extincteur, secours" },
    athlete = { name = "Athlete", summary = "Vitesse / mobilite", strengths = "Course, esquive, sorties" },
    eclaireur = { name = "Eclaireur", summary = "Reperage / guide", strengths = "Carte, discretion, info" },
    demolisseur = { name = "Demolisseur", summary = "Explosifs / chaos", strengths = "Bombes, molotovs, zone" },
    invincible = { name = "Invincible", summary = "Tout au max", strengths = "Armes, craft, soins, tank" },
    mule = { name = "Mule", summary = "Transport / stockage", strengths = "Gros sac, vivres, support" },
    builder = { name = "Builder", summary = "Construction / defense", strengths = "Ressources, poids illimite, refill" },
    civil = { name = "Civil", summary = "Mode difficile", strengths = "Survie pure, aucun bonus" },
}

Roles.ROLE_DEFS = {
    soldat = {
        name = "Soldat",
        skills = {
            {Perks.Aiming, 7},
            {Perks.Reloading, 7},
            {Perks.Strength, 5},
            {Perks.Fitness, 5},
            {Perks.Axe, 4},
            {Perks.SmallBlade, 4},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.M4A1", 1},
            {"Base.556Clip", 4},
            {"Base.556Bullets", 90},
            {"Base.Suppressor_Rifle", 1},
            {"Base.Sight_4xACOG", 1},
            {"Base.DEagle", 1},
            {"Base.44Clip", 2},
            {"Base.Bullets44", 30},
            {"Base.Light_Medium_SureFire_M952V", 1},
            {"Base.Screwdriver", 1},
            {"Base.HuntingKnife", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_D3M", 1},
        },
        bagContents = {
            {"Base.556Clip", 3},
            {"Base.556Bullets", 60},
            {"Base.44Clip", 1},
            {"Base.Bullets44", 16},
            {"Base.Bandage", 3},
            {"Base.TinnedSoup", 2},
        },
        equipped = {
            primary = "Base.M4A1",
            bag = "Base.Bag_D3M",
            clothes = {
                "Base.Military_Jumper",
                "Base.Military_Pants",
                "Base.Hat_FAST_Opscore",
                "Base.Tac_Boots",
                "Base.Glove_Mechanix",
            },
        },
        stats = { endurance = 0.5, panic = 20 },
    },
    voleur = {
        name = "Voleur",
        skills = {
            {Perks.Sneak, 8},
            {Perks.Lightfoot, 7},
            {Perks.Nimble, 6},
            {Perks.Sprinting, 5},
            {Perks.Strength, 4},
            {Perks.Fitness, 4},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.PPK", 1},
            {"Base.380Clip", 3},
            {"Base.Bullets380", 40},
            {"Base.Suppressor_Pistol", 1},
            {"Base.Crowbar", 1},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 2},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_D3M", 1},
        },
        bagContents = {
            {"Base.380Clip", 2},
            {"Base.Bullets380", 20},
            {"Base.Bandage", 2},
        },
        equipped = {
            primary = "Base.PPK",
            bag = "Base.Bag_D3M",
            clothes = {
                "Base.Tactical_Hood",
                "Base.Combat_Pants",
                "Base.Tac_Boots",
                "Base.Glove_Mechanix",
            },
        },
        stats = { endurance = 0.7, panic = 10 },
    },
    local_ = {
        name = "Local",
        skills = {
            {Perks.Carpentry, 6},
            {Perks.Cooking, 6},
            {Perks.Mechanics, 4},
            {Perks.Electrical, 4},
            {Perks.PlantScavenging, 5},
            {Perks.Strength, 4},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.Hammer", 1},
            {"Base.Saw", 1},
            {"Base.Screwdriver", 1},
            {"Base.Map", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 2},
            {"Base.TinnedSoup", 2},
            {"Base.Bag_NormalHikingBag", 1},
        },
        bagContents = {
            {"Base.Saw", 1},
            {"Base.Screwdriver", 1},
            {"Base.Map", 1},
            {"Base.Bandage", 3},
            {"Base.TinnedSoup", 2},
        },
        equipped = {
            primary = "Base.Hammer",
            bag = "Base.Bag_NormalHikingBag",
        },
        stats = { endurance = 0.4, panic = 25 },
    },
    medic = {
        name = "Medic",
        skills = {
            {Perks.Doctor, 8},
            {Perks.Strength, 3},
            {Perks.Fitness, 4},
            {Perks.SmallBlade, 4},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.KitchenKnife", 1},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 10},
            {"Base.AlcoholWipes", 5},
            {"Base.Splint", 3},
            {"Base.Pills", 3},
            {"Base.PillsBeta", 2},
            {"Base.PillsVitamins", 2},
            {"Base.Antibiotics", 2},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_DuffelBag", 1},
            {"Base.TinnedSoup", 2},
        },
        bagContents = {
            {"Base.Bandage", 10},
            {"Base.AlcoholWipes", 5},
            {"Base.Splint", 3},
            {"Base.Pills", 3},
            {"Base.PillsBeta", 2},
            {"Base.PillsVitamins", 2},
            {"Base.Antibiotics", 2},
            {"Base.TinnedSoup", 2},
        },
        equipped = {
            primary = "Base.KitchenKnife",
            bag = "Base.Bag_DuffelBag",
        },
        stats = { endurance = 0.4, panic = 20 },
    },
    rambo = {
        name = "Rambo",
        skills = {
            {Perks.Axe, 10},
            {Perks.Fitness, 8},
            {Perks.Strength, 7},
            {Perks.LongBlunt, 5},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.Axe", 1},
            {"Base.Machete", 1},
            {"Base.TAC15", 1},
            {"Base.Bolt_Bear", 10},
            {"Base.Bolt_Bear_Pack", 2},
            {"Base.Colt1911", 1},
            {"Base.45Clip", 3},
            {"Base.Bullets45", 30},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 4},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_X_Vest", 1},
        },
        bagContents = {
            {"Base.Machete", 1},
            {"Base.Bolt_Bear", 10},
            {"Base.45Clip", 2},
            {"Base.Bullets45", 20},
            {"Base.Bandage", 4},
            {"Base.TinnedBeans", 2},
        },
        equipped = {
            primary = "Base.Axe",
            bag = "Base.Bag_X_Vest",
            clothes = {
                "Base.Combat_Jumper",
                "Base.Combat_Pants",
                "Base.Maska_1_Helmet",
                "Base.Tac_Boots",
                "Base.Glove_Mechanix_Pact",
            },
        },
        stats = { endurance = 0.7, panic = 10 },
    },
    sniper = {
        name = "Sniper",
        skills = {
            {Perks.Aiming, 10},
            {Perks.Reloading, 8},
            {Perks.Sneak, 6},
            {Perks.Strength, 4},
            {Perks.Fitness, 4},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.M40A3", 1},
            {"Base.308Bullets", 60},
            {"Base.Sight_6xELCAN", 1},
            {"Base.Suppressor_Rifle", 1},
            {"Base.Revolver_Long_357", 1},
            {"Base.357Speed", 2},
            {"Base.Bullets357", 30},
            {"Base.Screwdriver", 1},
            {"Base.HuntingKnife", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_D3M", 1},
        },
        bagContents = {
            {"Base.308Bullets", 40},
            {"Base.357Speed", 1},
            {"Base.Bullets357", 18},
            {"Base.Bandage", 3},
            {"Base.TinnedSoup", 2},
        },
        equipped = {
            primary = "Base.M40A3",
            bag = "Base.Bag_D3M",
            clothes = {
                "Base.Gorka_Jacket_New",
                "Base.Gorka_Pants_New",
                "Base.Hat_PSGT_Helmet_Camo",
                "Base.Tac_Boots",
                "Base.Glove_Mechanix",
            },
        },
        stats = { endurance = 0.4, panic = 15 },
    },
    agent = {
        name = "007 Agent",
        skills = {
            {Perks.Aiming, 10},
            {Perks.Reloading, 10},
            {Perks.Sneak, 8},
            {Perks.Nimble, 8},
            {Perks.Lightfoot, 7},
            {Perks.Maintenance, 5},
            {Perks.Strength, 4},
            {Perks.Fitness, 5},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.PPK", 1},
            {"Base.380Clip", 3},
            {"Base.Bullets380", 40},
            {"Base.MP5SD6_Fixed", 1},
            {"Base.9mmClip", 4},
            {"Base.Bullets9mm", 60},
            {"Base.Suppressor_Pistol", 1},
            {"Base.Screwdriver", 1},
            {"Base.HuntingKnife", 1},
            {"Base.Bandage", 6},
            {"Base.WaterBottleFull", 1},
        },
        bagContents = {
            {"Base.380Clip", 2},
            {"Base.9mmClip", 3},
            {"Base.Bullets380", 20},
            {"Base.Bullets9mm", 30},
            {"Base.Suppressor_Pistol", 1},
            {"Base.Bandage", 3},
        },
        equipped = {
            primary = "Base.PPK",
            bag = "Base.Bag_Tactical_Belt_Front",
            clothes = {
                "Base.Suit_Wick",
                "Base.Suit_Trousers",
                "Base.DressShoes",
                "Base.Glove_Mechanix",
            },
        },
        stats = { endurance = 0.5, panic = 10 },
    },
    samourai = {
        name = "Samourai",
        skills = {
            {Perks.LongBlade, 10},
            {Perks.SmallBlade, 8},
            {Perks.Sprinting, 10},
            {Perks.Nimble, 8},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.Katana", 1},
            {"Base.Machete", 1},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_D3M", 1},
        },
        bagContents = {
            {"Base.Machete", 1},
            {"Base.Bandage", 3},
            {"Base.TinnedBeans", 2},
        },
        equipped = {
            primary = "Base.Katana",
            bag = "Base.Bag_D3M",
            clothes = {
                "Base.Ela_Jacket",
                "Base.Ela_Pants",
                "Base.Tac_Boots",
                "Base.Glove_Mechanix",
            },
        },
        stats = { endurance = 0.5, panic = 0 },
    },
    geek = {
        name = "Geek",
        skills = {
            {Perks.Electrical, 8},
            {Perks.Carpentry, 5},
            {Perks.Mechanics, 4},
            {Perks.Cooking, 3},
            {Perks.Strength, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.ElectronicsScrap", 5},
            {"Base.Screwdriver", 1},
            {"Base.DuctTape", 2},
            {"Base.Wire", 2},
            {"Base.Bandage", 2},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_NormalHikingBag", 1},
            {"Base.GranolaBar", 2},
        },
        bagContents = {
            {"Base.ElectronicsScrap", 5},
            {"Base.DuctTape", 2},
            {"Base.Wire", 2},
            {"Base.Bandage", 2},
            {"Base.GranolaBar", 2},
        },
        equipped = {
            primary = "Base.Screwdriver",
            bag = "Base.Bag_NormalHikingBag",
        },
        stats = { endurance = 0.3, panic = 30 },
    },
    survivaliste = {
        name = "Survivaliste",
        skills = {
            {Perks.Trapping, 8},
            {Perks.Aiming, 6},
            {Perks.Sneak, 5},
            {Perks.Strength, 4},
            {Perks.Fitness, 5},
            {Perks.Carpentry, 3},
        },
        items = {
            {"Base.HuntingRifle", 1},
            {"Base.3006Bullets", 60},
            {"Base.Sight_4xACOG", 1},
            {"Base.Revolver_Long_357", 1},
            {"Base.357Speed", 2},
            {"Base.Bullets357", 30},
            {"Base.TrapMouse", 3},
            {"Base.Screwdriver", 1},
            {"Base.HuntingKnife", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_D3M", 1},
        },
        bagContents = {
            {"Base.3006Bullets", 40},
            {"Base.357Speed", 1},
            {"Base.Bullets357", 18},
            {"Base.TrapMouse", 2},
            {"Base.Bandage", 3},
        },
        equipped = {
            primary = "Base.HuntingRifle",
            bag = "Base.Bag_D3M",
            clothes = {
                "Base.Gorka_Jacket_New",
                "Base.Gorka_Pants_New",
                "Base.Hat_PSGT_Helmet_Camo",
                "Base.Boots_Trackstar",
                "Base.Glove_Mechanix",
            },
        },
        stats = { endurance = 0.4, panic = 15 },
    },
    pompier = {
        name = "Pompier",
        skills = {
            {Perks.Strength, 8},
            {Perks.Fitness, 7},
            {Perks.Axe, 7},
            {Perks.LongBlunt, 5},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.Axe", 1},
            {"Base.Extinguisher", 1},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 5},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_ALICEpack", 1},
            {"Base.TinnedSoup", 2},
        },
        bagContents = {
            {"Base.Extinguisher", 1},
            {"Base.Bandage", 5},
            {"Base.TinnedSoup", 2},
        },
        equipped = {
            primary = "Base.Axe",

            bag = "Base.Bag_ALICEpack",
        },
        stats = { endurance = 0.6, panic = 10 },
    },
    athlete = {
        name = "Athlete",
        skills = {
            {Perks.Sprinting, 10},
            {Perks.Fitness, 10},
            {Perks.Nimble, 8},
            {Perks.Lightfoot, 7},
            {Perks.Strength, 4},
            {Perks.SmallBlade, 4},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.Machete", 1},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 1},
            {"Base.GranolaBar", 2},
            {"Base.Bag_Schoolbag", 1},
        },
        bagContents = {
            {"Base.GranolaBar", 2},
            {"Base.Bandage", 3},
        },
        equipped = {
            primary = "Base.Machete",
            bag = "Base.Bag_Schoolbag",
        },
        stats = { endurance = 0.4, panic = 15 },
    },
    eclaireur = {
        name = "Eclaireur",
        skills = {
            {Perks.Sneak, 8},
            {Perks.Lightfoot, 7},
            {Perks.Sprinting, 6},
            {Perks.Aiming, 5},
            {Perks.Fitness, 5},
            {Perks.SmallBlade, 5},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.MP7", 1},
            {"Base.9mmClip", 4},
            {"Base.Bullets9mm", 60},
            {"Base.Suppressor_Rifle", 1},
            {"Base.Hat_PVS15_ON", 1},
            {"Base.Map", 1},
            {"Base.Torch", 1},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 2},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_D3M", 1},
        },
        bagContents = {
            {"Base.9mmClip", 3},
            {"Base.Bullets9mm", 30},
            {"Base.Map", 1},
            {"Base.Torch", 1},
            {"Base.Bandage", 2},
        },
        equipped = {
            primary = "Base.MP7",
            bag = "Base.Bag_D3M",
            clothes = {
                "Base.Tactical_Hood",
                "Base.Combat_Pants",
                "Base.Hat_PVS15_ON",
                "Base.Tac_Boots",
                "Base.Glove_Mechanix",
            },
        },
        stats = { endurance = 0.3, panic = 20 },
    },
    demolisseur = {
        name = "Demolisseur",
        skills = {
            {Perks.Strength, 6},
            {Perks.Fitness, 5},
            {Perks.Axe, 5},
            {Perks.LongBlunt, 5},
            {Perks.Aiming, 5},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.M870_MCS", 1},
            {"Base.ShotgunShells", 24},
            {"Base.ShotgunShellsBox", 2},
            {"Base.Axe", 1},
            {"Base.PipeBomb", 5},
            {"Base.Aerosolbomb", 6},
            {"Base.AerosolbombTriggered", 3},
            {"Base.Molotov", 5},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 4},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_Tactical_Alice", 1},
        },
        bagContents = {
            {"Base.ShotgunShells", 18},
            {"Base.Axe", 1},
            {"Base.PipeBomb", 5},
            {"Base.Aerosolbomb", 6},
            {"Base.Molotov", 5},
            {"Base.Bandage", 4},
        },
        equipped = {
            primary = "Base.M870_MCS",
            bag = "Base.Bag_Tactical_Alice",
            clothes = {
                "Base.Combat_Jumper",
                "Base.Combat_Pants",
                "Base.EOD_Helmet",
                "Base.Tac_Boots",
                "Base.Glove_Mechanix_Pact",
            },
        },
        stats = { endurance = 0.6, panic = 10 },
    },
    invincible = {
        name = "Invincible",
        skills = {
            {Perks.Aiming, 10},
            {Perks.Reloading, 10},
            {Perks.Strength, 10},
            {Perks.Fitness, 10},
            {Perks.Sneak, 10},
            {Perks.Lightfoot, 10},
            {Perks.Nimble, 10},
            {Perks.Sprinting, 10},
            {Perks.Axe, 10},
            {Perks.LongBlade, 10},
            {Perks.SmallBlade, 10},
            {Perks.LongBlunt, 10},
            {Perks.SmallBlunt, 10},
            {Perks.Doctor, 10},
            {Perks.Carpentry, 10},
            {Perks.Mechanics, 10},
            {Perks.Electrical, 10},
            {Perks.Cooking, 10},
            {Perks.PlantScavenging, 10},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.M249", 1},
            {"Base.556Belt", 2},
            {"Base.556Bullets", 200},
            {"Base.Katana", 1},
            {"Base.Sledgehammer", 1},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 5},
            {"Base.PillsVitamins", 2},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_Tactical_Alice", 1},
        },
        bagContents = {
            {"Base.556Belt", 1},
            {"Base.556Bullets", 120},
            {"Base.Katana", 1},
            {"Base.Bandage", 5},
        },
        equipped = {
            primary = "Base.M249",
            bag = "Base.Bag_Tactical_Alice",
            clothes = {
                "Base.Combat_Jumper",
                "Base.Combat_Pants",
                "Base.EOD_Helmet",
                "Base.Tac_Boots",
                "Base.Glove_Mechanix_Pact",
            },
        },
        stats = { endurance = 0.8, panic = 5, fatigue = 0 },
    },
    mule = {
        name = "Mule",
        skills = {
            {Perks.Strength, 8},
            {Perks.Fitness, 6},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.Crowbar", 1},
            {"Base.Colt1911", 1},
            {"Base.45Clip", 2},
            {"Base.Bullets45", 28},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 2},
            {"Base.Bag_Tactical_Alice", 1},
        },
        bagContents = {
            {"Base.Bandage", 3},
            {"Base.TinnedBeans", 2},
            {"Base.TinnedSoup", 2},
        },
        equipped = {
            primary = "Base.Crowbar",
            bag = "Base.Bag_Tactical_Alice",
            clothes = {
                "Base.Military_Jumper",
                "Base.Military_Pants",
                "Base.Tac_Boots",
                "Base.Glove_Leather",
            },
        },
        stats = { endurance = 0.6, panic = 15 },
    },
    builder = {
        name = "Builder",
        skills = {
            {Perks.Carpentry, 10},
            {Perks.Electrical, 10},
            {Perks.MetalWelding, 10},
            {Perks.Mechanics, 10},
            {Perks.Tailoring, 10},
            {Perks.Cooking, 10},
            {Perks.Strength, 7},
            {Perks.Fitness, 5},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.Hammer", 1},
            {"Base.Saw", 1},
            {"Base.Screwdriver", 1},
            {"Base.Wrench", 1},
            {"Base.WeldingMask", 1},
            {"Base.BlowTorch", 1},
            {"Base.Crowbar", 1},
            {"Base.Sledgehammer", 1},
            {"Base.GardenSaw", 1},
            {"Base.Plank", 50},
            {"Base.Nails", 200},
            {"Base.SheetMetal", 20},
            {"Base.ScrapMetal", 30},
            {"Base.Wire", 10},
            {"Base.DuctTape", 10},
            {"Base.Rope", 5},
            {"Base.MetalPipe", 10},
            {"Base.Glue", 5},
            {"Base.MetalBar", 10},
            {"Base.Screws", 100},
            {"Base.Bandage", 5},
            {"Base.WaterBottleFull", 2},
            {"Base.TinnedBeans", 3},
            {"Base.TinnedSoup", 3},
            {"Base.Bag_BigHikingBag", 1},
            {"Base.Boilersuit", 1},
        },
        bagContents = {
            {"Base.Hammer", 1},
            {"Base.Saw", 1},
            {"Base.Screwdriver", 1},
            {"Base.Wrench", 1},
            {"Base.WeldingMask", 1},
            {"Base.BlowTorch", 1},
            {"Base.Sledgehammer", 1},
            {"Base.GardenSaw", 1},
            {"Base.Plank", 50},
            {"Base.Nails", 200},
            {"Base.SheetMetal", 20},
            {"Base.ScrapMetal", 30},
            {"Base.Wire", 10},
            {"Base.DuctTape", 10},
            {"Base.Rope", 5},
            {"Base.MetalPipe", 10},
            {"Base.Glue", 5},
            {"Base.MetalBar", 10},
            {"Base.Screws", 100},
            {"Base.Bandage", 5},
            {"Base.TinnedBeans", 3},
            {"Base.TinnedSoup", 3},
        },
        equipped = {
            primary = "Base.Crowbar",
            bag = "Base.Bag_BigHikingBag",
            clothes = {
                "Base.Boilersuit",
            },
        },
        stats = { endurance = 0.3, panic = 20 },
    },
    civil = {
        name = "Civil",
        skills = {
            {Perks.Fitness, 1},
            {Perks.Strength, 1},
            {Perks.Sneak, 1},
            {Perks.Lightfoot, 1},
            {Perks.Nimble, 1},
            {Perks.Carpentry, 3},
            {Perks.Trapping, 3},
        },
        items = {
            {"Base.KitchenKnife", 1},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 1},
            {"Base.WaterBottleFull", 1},
            {"Base.GranolaBar", 2},
            {"Base.Bag_Schoolbag", 1},
            {"Base.Torch", 1},
            {"Base.Battery", 1},
        },
        bagContents = {
            {"Base.Bandage", 1},
            {"Base.GranolaBar", 2},
            {"Base.Torch", 1},
            {"Base.Battery", 1},
        },
        equipped = {
            primary = "Base.KitchenKnife",
            bag = "Base.Bag_Schoolbag",
        },
        stats = { panic = 50, endurance = 0.2, fatigue = 0.15 },
    },
}

Roles.BUILDER_REFILL_ITEMS = {
    {"Base.Plank", 50},
    {"Base.Nails", 200},
    {"Base.SheetMetal", 20},
    {"Base.ScrapMetal", 30},
    {"Base.Wire", 10},
    {"Base.DuctTape", 10},
    {"Base.Rope", 5},
    {"Base.MetalPipe", 10},
    {"Base.Glue", 5},
    {"Base.MetalBar", 10},
    {"Base.Screws", 100},
    -- Food / water kept in the builder refill inventory.
    {"Base.TinnedBeans", 5},
    {"Base.TinnedSoup", 5},
    {"Base.TunaTin", 5},
    {"Base.CannedSardines", 4},
    {"Base.CannedChili", 4},
    {"Base.CannedCorn", 4},
    {"Base.CannedPeas", 4},
    {"Base.CannedCarrots", 4},
    {"Base.CannedPotato", 4},
    {"Base.CannedTomato", 4},
    {"Base.CannedPeaches", 3},
    {"Base.CannedPineapple", 3},
    {"Base.CannedMushroomSoup", 3},
    {"Base.CannedCornedBeef", 3},
    {"Base.PeanutButter", 3},
    {"Base.Honey", 2},
    {"Base.Chocolate", 4},
    {"Base.Crisps", 4},
    {"Base.Popcorn", 3},
    {"Base.Peanuts", 4},
    {"Base.Cereal", 3},
    {"Base.Oats", 3},
    {"Base.Rice", 3},
    {"Base.Pasta", 3},
    {"Base.GranolaBar", 4},
    {"Base.GrahamCrackers", 3},
    {"Base.BreadSlices", 3},
    {"Base.Cheese", 3},
    {"Base.Milk", 2},
    {"Base.Pickles", 2},
    {"Base.JamFruit", 2},
    {"Base.WaterBottleFull", 6},
}

Roles.COMMUNITY_STOCK_ITEMS = {
    -- Food
    {"Base.TinnedBeans", 5},
    {"Base.TinnedSoup", 5},
    {"Base.TunaTin", 5},
    {"Base.CannedSardines", 4},
    {"Base.CannedChili", 4},
    {"Base.CannedCorn", 4},
    {"Base.CannedPeas", 4},
    {"Base.CannedCarrots", 4},
    {"Base.CannedPotato", 4},
    {"Base.CannedTomato", 4},
    {"Base.CannedPeaches", 3},
    {"Base.CannedPineapple", 3},
    {"Base.CannedMushroomSoup", 3},
    {"Base.CannedCornedBeef", 3},
    {"Base.PeanutButter", 3},
    {"Base.Honey", 2},
    {"Base.Chocolate", 4},
    {"Base.Crisps", 4},
    {"Base.Popcorn", 3},
    {"Base.Peanuts", 4},
    {"Base.Cereal", 3},
    {"Base.Oats", 3},
    {"Base.Rice", 3},
    {"Base.Pasta", 3},
    {"Base.GranolaBar", 4},
    {"Base.GrahamCrackers", 3},
    {"Base.BreadSlices", 3},
    {"Base.Cheese", 3},
    {"Base.Milk", 2},
    {"Base.Pickles", 2},
    {"Base.JamFruit", 2},
    -- Water
    {"Base.WaterBottleFull", 6},
    -- Ammo
    {"Base.9mmClip", 2},
    {"Base.Bullets9mm", 24},
    {"Base.308Clip", 2},
    {"Base.308Bullets", 16},
    {"Base.556Clip", 2},
    {"Base.556Bullets", 24},
}

return Roles
