LastHomeRoles = LastHomeRoles or {}

local Roles = LastHomeRoles

Roles.MODULE = "LastHome"

Roles.ROLE_ORDER = {
    "soldat", "voleur", "local_", "medic",
    "rambo", "sniper", "samourai", "geek",
    "survivaliste", "pompier", "athlete", "eclaireur",
    "demolisseur", "invincible", "mule", "builder",
    "civil",
}

Roles.ROLE_NAMES = {
    soldat = "Soldat",
    voleur = "Voleur",
    local_ = "Local",
    medic = "Medic",
    rambo = "Rambo",
    sniper = "Sniper",
    samourai = "Samourai",
    geek = "Geek",
    survivaliste = "Survivaliste",
    pompier = "Pompier",
    athlete = "Athlete",
    eclaireur = "Eclaireur",
    demolisseur = "Demolisseur",
    invincible = "Invincible",
    mule = "Mule",
    builder = "Builder",
    civil = "Civil",
}

Roles.ROLE_INFO = {
    soldat = { name = "Soldat", summary = "Combat / defense", strengths = "Tir, couverture, melee" },
    voleur = { name = "Voleur", summary = "Loot furtif", strengths = "Crowbar, discretion, sorties" },
    local_ = { name = "Local", summary = "Reparations / ressources", strengths = "Outils, craft, logistique" },
    medic = { name = "Medic", summary = "Soin / support", strengths = "Soins lourds, stabilisation" },
    rambo = { name = "Rambo", summary = "Tank melee", strengths = "Hache, endurance, breches" },
    sniper = { name = "Sniper", summary = "Longue distance", strengths = ".308, lunette, couverture" },
    samourai = { name = "Samourai", summary = "Katana / mobilite", strengths = "Lames, vitesse, precision" },
    geek = { name = "Geek", summary = "Electronique / pieges", strengths = "Bidouille, alarmes, gadgets" },
    survivaliste = { name = "Survivaliste", summary = "Nature / autonomie", strengths = "Pieges, loot, autonomie" },
    pompier = { name = "Pompier", summary = "Sauvetage / anti-feu", strengths = "Hache, extincteur, secours" },
    athlete = { name = "Athlete", summary = "Vitesse / mobilite", strengths = "Course, esquive, sorties" },
    eclaireur = { name = "Eclaireur", summary = "Reperage / guide", strengths = "Carte, discretion, info" },
    demolisseur = { name = "Demolisseur", summary = "Explosifs / chaos", strengths = "Bombes, molotovs, zone" },
    invincible = { name = "Invincible", summary = "Tout au max", strengths = "Armes, craft, soins, tank" },
    mule = { name = "Mule", summary = "Transport / stockage", strengths = "Gros sac, vivres, support" },
    builder = { name = "Builder", summary = "Construction / defense", strengths = "Ressources, poids illimite, refill" },
    civil = { name = "Civil", summary = "Mode difficile", strengths = "Survie pure, aucun bonus" },
}

Roles.ROLE_DEFS = {
    soldat = {
        name = "Soldat",
        skills = {
            {Perks.Aiming, 7},
            {Perks.Reloading, 7},
            {Perks.Strength, 5},
            {Perks.Fitness, 5},
            {Perks.Axe, 4},
            {Perks.SmallBlade, 4},
        },
        items = {
            {"Base.Pistol", 1},
            {"Base.9mmClip", 2},
            {"Base.Bullets9mm", 30},
            {"Base.HuntingKnife", 1},
            {"Base.Bandage", 4},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_DuffelBag", 1},
            {"Base.Torch", 1},
            {"Base.Battery", 1},
        },
        bagContents = {
            {"Base.Bullets9mm", 30},
            {"Base.Bandage", 2},
        },
        equipped = {
            primary = "Base.Pistol",
            secondary = "Base.HuntingKnife",
            bag = "Base.Bag_DuffelBag",
        },
        stats = { endurance = 0.5, panic = 20 },
    },
    voleur = {
        name = "Voleur",
        skills = {
            {Perks.Sneak, 8},
            {Perks.Lightfoot, 8},
            {Perks.Nimble, 8},
            {Perks.Sprinting, 6},
            {Perks.LongBlunt, 4},
            {Perks.Strength, 3},
        },
        items = {
            {"Base.Crowbar", 1},
            {"Base.Screwdriver", 1},
            {"Base.Bandage", 2},
            {"Base.WaterBottleFull", 1},
            {"Base.TinnedBeans", 1},
            {"Base.Bag_Schoolbag", 1},
            {"Base.Torch", 1},
            {"Base.Battery", 1},
        },
        bagContents = {
            {"Base.Bandage", 2},
            {"Base.TinnedBeans", 1},
        },
        equipped = {
            primary = "Base.Crowbar",
            secondary = "Base.Screwdriver",
            bag = "Base.Bag_Schoolbag",
        },
        stats = { endurance = 0.3, panic = 15 },
    },
    local_ = {
        name = "Local",
        skills = {
            {Perks.Carpentry, 6},
            {Perks.Cooking, 6},
            {Perks.Mechanics, 4},
            {Perks.Electricity, 4},
            {Perks.PlantScavenging, 5},
            {Perks.Strength, 4},
        },
        items = {
            {"Base.Hammer", 1},
            {"Base.Saw", 1},
            {"Base.Screwdriver", 1},
            {"Base.Map", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 2},
            {"Base.TinnedSoup", 2},
            {"Base.Bag_NormalHikingBag", 1},
        },
        bagContents = {
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 2},
            {"Base.TinnedSoup", 2},
        },
        equipped = {
            primary = "Base.Hammer",
            secondary = "Base.Screwdriver",
            bag = "Base.Bag_NormalHikingBag",
        },
        stats = { endurance = 0.4, panic = 25 },
    },
    medic = {
        name = "Medic",
        skills = {
            {Perks.Doctor, 8},
            {Perks.Strength, 3},
            {Perks.Fitness, 4},
            {Perks.SmallBlade, 4},
        },
        items = {
            {"Base.KitchenKnife", 1},
            {"Base.Bandage", 10},
            {"Base.AlcoholWipes", 5},
            {"Base.Splint", 3},
            {"Base.Pills", 3},
            {"Base.PillsBeta", 2},
            {"Base.PillsVitamins", 2},
            {"Base.Antibiotics", 2},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_DuffelBag", 1},
        },
        bagContents = {
            {"Base.Bandage", 10},
            {"Base.AlcoholWipes", 5},
            {"Base.Splint", 3},
            {"Base.Pills", 3},
            {"Base.PillsBeta", 2},
            {"Base.PillsVitamins", 2},
            {"Base.Antibiotics", 2},
        },
        equipped = {
            primary = "Base.KitchenKnife",
            bag = "Base.Bag_DuffelBag",
        },
        stats = { endurance = 0.4, panic = 20 },
    },
    rambo = {
        name = "Rambo",
        skills = {
            {Perks.Strength, 10},
            {Perks.Fitness, 8},
            {Perks.Axe, 8},
            {Perks.LongBlade, 6},
            {Perks.Sprinting, 4},
        },
        items = {
            {"Base.Axe", 1},
            {"Base.Machete", 1},
            {"Base.Bandage", 5},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_NormalHikingBag", 1},
        },
        bagContents = {
            {"Base.Bandage", 5},
            {"Base.WaterBottleFull", 1},
        },
        equipped = {
            primary = "Base.Axe",
            secondary = "Base.Machete",
            bag = "Base.Bag_NormalHikingBag",
        },
        stats = { endurance = 0.7, panic = 10 },
    },
    sniper = {
        name = "Sniper",
        skills = {
            {Perks.Aiming, 10},
            {Perks.Reloading, 8},
            {Perks.Sneak, 6},
            {Perks.Strength, 4},
            {Perks.Fitness, 4},
        },
        items = {
            {"Base.HuntingRifle", 1},
            {"Base.308Clip", 1},
            {"Base.308Bullets", 50},
            {"Base.x4Scope", 1},
            {"Base.HuntingKnife", 1},
            {"Base.Bandage", 2},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_NormalHikingBag", 1},
        },
        bagContents = {
            {"Base.308Bullets", 50},
            {"Base.Bandage", 2},
        },
        equipped = {
            primary = "Base.HuntingRifle",
            secondary = "Base.HuntingKnife",
            bag = "Base.Bag_NormalHikingBag",
        },
        stats = { endurance = 0.4, panic = 15 },
    },
    samourai = {
        name = "Samourai",
        skills = {
            {Perks.LongBlade, 10},
            {Perks.SmallBlade, 8},
            {Perks.Sprinting, 8},
            {Perks.Nimble, 8},
            {Perks.Fitness, 7},
            {Perks.Strength, 5},
        },
        items = {
            {"Base.Katana", 1},
            {"Base.Machete", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_NormalHikingBag", 1},
        },
        bagContents = {
            {"Base.Bandage", 3},
        },
        equipped = {
            primary = "Base.Katana",
            secondary = "Base.Machete",
            bag = "Base.Bag_NormalHikingBag",
        },
        stats = { endurance = 0.5, panic = 10 },
    },
    geek = {
        name = "Geek",
        skills = {
            {Perks.Electricity, 8},
            {Perks.Carpentry, 5},
            {Perks.Mechanics, 4},
            {Perks.Cooking, 3},
            {Perks.Strength, 3},
        },
        items = {
            {"Base.ElectronicsScrap", 5},
            {"Base.Screwdriver", 1},
            {"Base.DuctTape", 2},
            {"Base.Wire", 2},
            {"Base.Bandage", 2},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_NormalHikingBag", 1},
        },
        bagContents = {
            {"Base.ElectronicsScrap", 5},
            {"Base.DuctTape", 2},
            {"Base.Wire", 2},
        },
        equipped = {
            primary = "Base.Screwdriver",
            bag = "Base.Bag_NormalHikingBag",
        },
        stats = { endurance = 0.3, panic = 30 },
    },
    survivaliste = {
        name = "Survivaliste",
        skills = {
            {Perks.PlantScavenging, 8},
            {Perks.Trapping, 8},
            {Perks.Aiming, 6},
            {Perks.Sneak, 6},
            {Perks.Carpentry, 4},
            {Perks.Cooking, 5},
        },
        items = {
            {"Base.HuntingRifle", 1},
            {"Base.308Bullets", 24},
            {"Base.Bag_ALICEpack", 1},
            {"Base.DuctTape", 2},
            {"Base.Rope", 2},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 2},
            {"Base.TinnedBeans", 2},
        },
        bagContents = {
            {"Base.DuctTape", 2},
            {"Base.Rope", 2},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 2},
        },
        equipped = {
            primary = "Base.HuntingRifle",
            bag = "Base.Bag_ALICEpack",
        },
        stats = { endurance = 0.4, panic = 15 },
    },
    pompier = {
        name = "Pompier",
        skills = {
            {Perks.Strength, 8},
            {Perks.Fitness, 7},
            {Perks.Axe, 7},
            {Perks.LongBlunt, 5},
        },
        items = {
            {"Base.Axe", 1},
            {"Base.Extinguisher", 1},
            {"Base.Bandage", 5},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_ALICEpack", 1},
        },
        bagContents = {
            {"Base.Bandage", 5},
        },
        equipped = {
            primary = "Base.Axe",
            bag = "Base.Bag_ALICEpack",
        },
        stats = { endurance = 0.6, panic = 10 },
    },
    athlete = {
        name = "Athlete",
        skills = {
            {Perks.Sprinting, 10},
            {Perks.Fitness, 10},
            {Perks.Nimble, 8},
            {Perks.Lightfoot, 7},
            {Perks.Strength, 4},
            {Perks.SmallBlade, 4},
        },
        items = {
            {"Base.Machete", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 1},
            {"Base.GranolaBar", 2},
            {"Base.Bag_Schoolbag", 1},
        },
        bagContents = {
            {"Base.GranolaBar", 2},
            {"Base.Bandage", 3},
        },
        equipped = {
            primary = "Base.Machete",
            bag = "Base.Bag_Schoolbag",
        },
        stats = { endurance = 0.4, panic = 15 },
    },
    eclaireur = {
        name = "Eclaireur",
        skills = {
            {Perks.Sneak, 8},
            {Perks.Lightfoot, 7},
            {Perks.Sprinting, 6},
            {Perks.Aiming, 5},
            {Perks.Fitness, 5},
            {Perks.SmallBlade, 5},
        },
        items = {
            {"Base.Machete", 1},
            {"Base.Map", 1},
            {"Base.Torch", 1},
            {"Base.Bandage", 2},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_Schoolbag", 1},
        },
        bagContents = {
            {"Base.Map", 1},
            {"Base.Bandage", 2},
        },
        equipped = {
            primary = "Base.Machete",
            bag = "Base.Bag_Schoolbag",
        },
        stats = { endurance = 0.3, panic = 20 },
    },
    demolisseur = {
        name = "Demolisseur",
        skills = {
            {Perks.Strength, 6},
            {Perks.Fitness, 5},
            {Perks.Axe, 5},
            {Perks.LongBlunt, 5},
            {Perks.Aiming, 4},
            {Perks.Electricity, 8},
            {Perks.Mechanics, 7},
        },
        items = {
            {"Base.PipeBomb", 6},
            {"Base.PipeBombTriggered", 3},
            {"Base.Aerosolbomb", 6},
            {"Base.AerosolbombTriggered", 3},
            {"Base.Molotov", 5},
            {"Base.Sledgehammer", 1},
            {"Base.Lighter", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 1},
            {"Base.Bag_ALICEpack", 1},
        },
        bagContents = {
            {"Base.PipeBomb", 6},
            {"Base.PipeBombTriggered", 3},
            {"Base.Aerosolbomb", 6},
            {"Base.AerosolbombTriggered", 3},
            {"Base.Molotov", 5},
        },
        equipped = {
            primary = "Base.Sledgehammer",
            bag = "Base.Bag_ALICEpack",
        },
        stats = { endurance = 0.5, panic = 15 },
    },
    invincible = {
        name = "Invincible",
        skills = {
            {Perks.Aiming, 10},
            {Perks.Reloading, 10},
            {Perks.Strength, 10},
            {Perks.Fitness, 10},
            {Perks.Sneak, 10},
            {Perks.Lightfoot, 10},
            {Perks.Nimble, 10},
            {Perks.Sprinting, 10},
            {Perks.Axe, 10},
            {Perks.LongBlade, 10},
            {Perks.SmallBlade, 10},
            {Perks.LongBlunt, 10},
            {Perks.SmallBlunt, 10},
            {Perks.Doctor, 10},
            {Perks.Carpentry, 10},
            {Perks.Mechanics, 10},
            {Perks.Electricity, 10},
            {Perks.Cooking, 10},
            {Perks.PlantScavenging, 10},
        },
        items = {
            {"Base.AssaultRifle", 1},
            {"Base.556Clip", 3},
            {"Base.556Bullets", 60},
            {"Base.Katana", 1},
            {"Base.Sledgehammer", 1},
            {"Base.Bandage", 5},
            {"Base.AlcoholWipes", 3},
            {"Base.Splint", 2},
            {"Base.Pills", 2},
            {"Base.PillsBeta", 1},
            {"Base.PillsVitamins", 1},
            {"Base.Antibiotics", 1},
            {"Base.WaterBottleFull", 2},
            {"Base.Map", 1},
            {"Base.Bag_ALICEpack_Army", 1},
            {"Base.Torch", 1},
            {"Base.Battery", 2},
        },
        bagContents = {
            {"Base.556Clip", 3},
            {"Base.556Bullets", 60},
            {"Base.Bandage", 5},
            {"Base.AlcoholWipes", 3},
            {"Base.Splint", 2},
            {"Base.Pills", 2},
        },
        equipped = {
            primary = "Base.AssaultRifle",
            secondary = "Base.Katana",
            bag = "Base.Bag_ALICEpack_Army",
        },
        stats = { endurance = 0.8, panic = 5, fatigue = 0 },
    },
    mule = {
        name = "Mule",
        skills = {
            {Perks.Strength, 10},
            {Perks.Fitness, 7},
            {Perks.Sprinting, 10},
            {Perks.Carpentry, 4},
        },
        items = {
            {"Base.Bag_ALICEpack_Army", 1},
            {"Base.Bag_DuffelBag", 1},
            {"Base.Crowbar", 1},
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 2},
            {"Base.TinnedBeans", 3},
            {"Base.TinnedSoup", 3},
            {"Base.TinOpener", 1},
            {"Base.PetrolCan", 1},
        },
        bagContents = {
            {"Base.Bandage", 3},
            {"Base.WaterBottleFull", 2},
            {"Base.TinnedBeans", 3},
            {"Base.TinnedSoup", 3},
        },
        equipped = {
            primary = "Base.Crowbar",
            bag = "Base.Bag_ALICEpack_Army",
        },
        stats = { endurance = 0.5, panic = 25 },
    },
    builder = {
        name = "Builder",
        skills = {
            {Perks.Carpentry, 10},
            {Perks.Electricity, 10},
            {Perks.MetalWelding, 10},
            {Perks.Mechanics, 10},
            {Perks.Tailoring, 10},
            {Perks.Cooking, 10},
            {Perks.Strength, 7},
            {Perks.Fitness, 5},
        },
        items = {
            {"Base.Hammer", 1},
            {"Base.Saw", 1},
            {"Base.Screwdriver", 1},
            {"Base.Wrench", 1},
            {"Base.WeldingMask", 1},
            {"Base.BlowTorch", 1},
            {"Base.Crowbar", 1},
            {"Base.Sledgehammer", 1},
            {"Base.GardenSaw", 1},
            {"Base.Plank", 50},
            {"Base.Nails", 200},
            {"Base.SheetMetal", 20},
            {"Base.ScrapMetal", 30},
            {"Base.Wire", 10},
            {"Base.DuctTape", 10},
            {"Base.Rope", 5},
            {"Base.MetalPipe", 10},
            {"Base.Glue", 5},
            {"Base.MetalBar", 10},
            {"Base.Screws", 100},
            {"Base.Bandage", 5},
            {"Base.WaterBottleFull", 2},
            {"Base.TinnedBeans", 3},
            {"Base.TinnedSoup", 3},
            {"Base.Bag_BigHikingBag", 1},
            {"Base.Boilersuit", 1},
        },
        bagContents = {
            {"Base.Plank", 20},
            {"Base.Nails", 80},
            {"Base.SheetMetal", 8},
            {"Base.ScrapMetal", 12},
            {"Base.Wire", 4},
            {"Base.DuctTape", 4},
            {"Base.Rope", 2},
            {"Base.MetalPipe", 4},
            {"Base.Glue", 2},
            {"Base.MetalBar", 4},
            {"Base.Screws", 40},
            {"Base.Bandage", 5},
            {"Base.WaterBottleFull", 2},
        },
        equipped = {
            primary = "Base.Crowbar",
            bag = "Base.Bag_BigHikingBag",
            clothes = {
                "Base.Boilersuit",
            },
        },
        stats = { endurance = 0.3, panic = 20 },
    },
    civil = {
        name = "Civil",
        skills = {
            {Perks.Fitness, 1},
            {Perks.Strength, 1},
            {Perks.Sneak, 1},
            {Perks.Lightfoot, 1},
            {Perks.Nimble, 1},
        },
        items = {
            {"Base.KitchenKnife", 1},
            {"Base.Bandage", 1},
            {"Base.WaterBottleFull", 1},
            {"Base.GranolaBar", 1},
            {"Base.Bag_Schoolbag", 1},
            {"Base.Torch", 1},
            {"Base.Battery", 1},
        },
        equipped = {
            primary = "Base.KitchenKnife",
            bag = "Base.Bag_Schoolbag",
        },
        stats = { panic = 50, endurance = 0.2, fatigue = 0.15 },
    },
}

Roles.BUILDER_REFILL_ITEMS = {
    {"Base.Plank", 50},
    {"Base.Nails", 200},
    {"Base.SheetMetal", 20},
    {"Base.ScrapMetal", 30},
    {"Base.Wire", 10},
    {"Base.DuctTape", 10},
    {"Base.Rope", 5},
    {"Base.MetalPipe", 10},
    {"Base.Glue", 5},
    {"Base.MetalBar", 10},
    {"Base.Screws", 100},
}

return Roles
